name: Check generated docs

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: actions/checkout@v4.2.2

      - name: Generate docs
        run: |
          nix-instantiate --eval --strict --quiet --json dev/generate-docs/get-docs.nix \
            | jq \
            | sed 's/^  },$/  },\n/' \
            | sed 's/\\n"/"/' \
            | sed -r 's/(\\n)+/ /g' \
            > temp.json

      - name: Check that generated docs are the same
        run: diff -q temp.json docs/options.json
